### ISSUE TITLE
css class and id autocompletion not showing all classes in LESS

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1092]
The css autocompletion is not working as intended in LESS, it is showing only a few classes.
If i use css it's working better.

![snap 2016-02-19 at 16 28 52](https://cloud.githubusercontent.com/assets/3530262/13179864/4e2981e0-d726-11e5-9170-111265d88417.png)

**Comment by mitchell-as** [comment]
In order to fix this, would you please give a text example of some source and expected completions? From your picture it is not clear what the completions should be. I need this information for writing my unit tests. Thanks!

**Comment by babobski** [comment]
Ok, will create some tests, i will come back on this tommorow. (weekend has begon :beers: )

**Comment by babobski** [comment]
Just a test case to begin, the auto completion and sidebar can't handel nestded classes or id's.
If you try this you will only get the "root" class:
```less
.test {
    .testClass {
        
    }
}
```
You will only get result for `test`
![snap 2016-02-19 at 19 05 48](https://cloud.githubusercontent.com/assets/3530262/13184426/0e4e8b54-d73c-11e5-8585-f9c02a72f2c6.png)

And also for  the sidebar:
![snap 2016-02-19 at 19 11 10](https://cloud.githubusercontent.com/assets/3530262/13184501/a330ec1c-d73c-11e5-8704-988713ba1a7a.png)
And for a good test case:
```less
.test {
    color: #333;
    .control-label {
        font-size: 12px;
        color: #a70713;
    }
    .btn {
        background-color: #fff;
        color: #333;
        -webkit-transition: all 200ms ease;
        transition: all 200ms ease;
        &.green {
            background-color: #0f9920;
            -webkit-transition: all 200ms ease;
            transition: all 200ms ease;
            :hover, &:active, &:focus {
                color: #000;
                background-color: #26771e;
            }
        }
        &:hover, &:active, &:focus {
            color: #000;
            background-color: #efefef;
        }
    }
}
```
And that will compile into:
```css
.test {
  color: #333;
}
.test .control-label {
  font-size: 12px;
  color: #a70713;
}
.test .btn {
  background-color: #fff;
  color: #333;
  -webkit-transition: all 200ms ease;
  transition: all 200ms ease;
}
.test .btn.green {
  background-color: #0f9920;
  -webkit-transition: all 200ms ease;
  transition: all 200ms ease;
}
.test .btn.green :hover,
.test .btn.green:active,
.test .btn.green:focus {
  color: #000;
  background-color: #26771e;
}
.test .btn:hover,
.test .btn:active,
.test .btn:focus {
  color: #000;
  background-color: #efefef;
}
```
