### ISSUE TITLE
Code side pane can't handle nested less, scss and sass

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1093]
The Code side pane is not showing all nested elements, it only showing a few elements (the same elements that are shown for the autocompletion)

![snap 2016-02-19 at 16 37 36](https://cloud.githubusercontent.com/assets/3530262/13180047/1bf26484-d727-11e5-9e0c-07dda757d20f.png)

**Comment by mitchell-as** [comment]
That looks like there might be a parsing error. If possible, would you please provide an example of source that does not show up properly in the code browser? That would make it easier to write a unit test case for. Thanks!

**Comment by babobski** [comment]
Will do

**Comment by babobski** [comment]
For scss you can use the same test as in #1092, the nesting is the same and I'm not using any vararibles.
For SASS you can use the same test only without all the decoration
```sass
.test 
    color: #333
    .control-label 
        font-size: 12px
        color: #a70713
    .btn 
        background-color: #fff
        color: #333
        -webkit-transition: all 200ms ease
        transition: all 200ms ease
        &.green 
            background-color: #0f9920
            -webkit-transition: all 200ms ease
            transition: all 200ms ease
           & :hover, &:active, &:focus 
                color: #000
                background-color: #26771e
        &:hover, &:active, &:focus 
            color: #000
            background-color: #efefef
```
Adn will also compile in:
```css
.test {
	color: #333;
}

.test .control-label {
	font-size: 12px;
	color: #a70713;
}

.test .btn {
	background-color: #fff;
	color: #333;
	-webkit-transition: all 200ms ease;
	transition: all 200ms ease;
}

.test .btn.green {
	background-color: #0f9920;
	-webkit-transition: all 200ms ease;
	transition: all 200ms ease;
}

.test .btn.green:hover,
.test .btn.green:active,
.test .btn.green:focus {
	color: #000;
	background-color: #26771e;
}

.test .btn:hover,
.test .btn:active,
.test .btn:focus {
	color: #000;
	background-color: #efefef;
}
```
