### ISSUE TITLE
Color popup appears under the mouse: unable to click on a hyperlink

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1335]
### Short Summary

title

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04

### Workaround

Thanks to @babobski:

```css
#colorpicker_swatch_popup {
    margin-left: -110px !important;
}
```
