### ISSUE TITLE
Cant edit colors in css with colorpicker

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1478]
### Short Summary
Unable to trigger the colorpicker in css files to edit colors

### Steps to Reproduce
Open a css file, and try to edit the color using ctrl + click, the color preview is showing. But I'm unable to open the color picker for editing the color.

### Expected results
Color picker will open

### Actual results
No color picker is triggered

### Platform Information
Komodo edit 10

**Comment by Naatan** [comment]
Check out Prefs > Editor > Smart Editing > Hyperlinks

Are those options checked?

**Comment by babobski** [comment]
Just checked, but those options where unchecked. Checked them but still can't trigger the colorpicker, even after a restart. Looks like the preview is preventing me to click on the hyperlink

**Comment by mitchell-as** [comment]
In Komodo 9 the color preview shows below the current line. In Komodo X the color preview shows at the mouse position, making the click impossible.

**Comment by babobski** [comment]
Just added a small work around in my skin.
Just added a little css to the color preview.
I just add these line of less in my [custom less](http://forum.komodoide.com/t/komodo-x-customization-tips-tricks/2749#post_1), and can now click on the hyperlink.
```less
// Moves the preview to the left side of the cursor
#colorpicker_swatch_popup {
	margin-left: -110px !important;
}

// First added these lines only the preview sometimes overlays the colorpicker
//#colorpicker_swatch_popup {
//	margin-left: 10px !important;
//}
```
