### ISSUE TITLE
Prefwindow is missing binding

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1506]
In the prefwindow the buttons are missing.
![ded8ede085b1b7a557c22cbe6c81becb36e0f0a3](https://cloud.githubusercontent.com/assets/3530262/15339824/8b563d9c-1c86-11e6-8f4b-7c729f1a9872.png)

When adding the binding back the buttons appear.
```css
prefwindow,
prefwindow:root /* override :root from above */ {
  -moz-binding: url("chrome://global/content/bindings/preferences.xml#prefwindow");
}
```
![2016-05-17 23_25_24](https://cloud.githubusercontent.com/assets/3530262/15339849/b26df898-1c86-11e6-818a-93970b43d98a.png)
