### ISSUE TITLE
Missing styling for web notifications

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1573]
### Short Summary
The web notifications aren't styled, when you use the default skin, the editor is dark but the notifications have a light background and grey text.

### Platform Information

Komodo 10

### Additional Information
To work around the issue you can add these lines of less in your skin:
```less
.alertBox {
	background: darken(@background, 5%) !important;
	border: darken(@background, 10%) !important;
}

.alertImageBox {
	background: darken(@background, 5%) !important;
	border: darken(@background, 10%) !important;
}

.alertTextBox, .alertCloseBox {
	background: darken(@background, 5%) !important;
}
```
