### ISSUE TITLE
Auto-complete for SCSS mixins

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1667]
### Short Summary

```scss
@mixin komodo($color) {
  color: $color;
  &:before {
    content: "Komodo";
  }
}


.komodo {
  @include |
}
```
There's no `komodo` in auto-complete popup at `|` position, but there are a lot of HTML tags (a, div, etc.), ids and classes defined in the file, which is invalid.

Auto-complete should show `komodo` only.
