### ISSUE TITLE
Sections breaks with this sample code

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1844]
### Short Summary

```scss
pre, code {
    background: rgba($base, 0.08);
}

.div.div {
    color: red;
}
```

Open Sections scope of Commando or Code Toolbox - you won't see `.div.div` anywhere. Remove `rgba($base, 0.08)` and replace it with `red` and everything will work fine.

**Comment by Defman21** [comment]
If you comment `rgba`:
```scss
pre, code {
    background: #ff0000; //rgba($base0D, 0.08);
}

.div.div {
    color: red;
}
```

Code will be:

![img](http://imgur.com/qtnLHtv.png)
