### ISSUE TITLE
Toolbar icon color colors both top icons and side icons

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1962]
### Short Summary
When you use the color editor, you can set the toolbar icon color, only this affects the icons in the top bar and the icons in the left sidebar. These items should be controlled separate.
![2016-08-24 07_44_43](https://cloud.githubusercontent.com/assets/3530262/17919521/89c2a6e2-69ce-11e6-81bf-5c99327583c8.png)
Now I can't see the icons in the sidebar anymore.
![2016-08-24 07_45_26](https://cloud.githubusercontent.com/assets/3530262/17919536/a25062a8-69ce-11e6-8b19-d34d783f0633.png)

### Expected results
That you can control these items separate from each other.

### Platform Information
Komodo Ide 10.1

### Additional Information
As workaround you probably can fix this with a bit of custom css

**Comment by Naatan** [comment]
This is fixed in the release build, sounds like you're still on the beta.

**Comment by babobski** [comment]
@Naatan if i'm correct I'm not using the beta.
```
[2016-08-24 20:06:38,395] [INFO] Startup: Welcome to Komodo IDE 10.1.0 build 89455 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
```

**Comment by Naatan** [comment]
Can you share a color scheme that reproduces the issue?

**Comment by babobski** [comment]
You can find the color scheme of the screenshots [here](https://github.com/babobski/Stormy-grey)

**Comment by Defman21** [comment]
Able to reproduce it with the Redmond color scheme.

**Comment by babobski** [comment]
Changing the color to the editor foreground fixes the issue.

```css
#komodo_main #toolbox_side toolbaritem > toolbarbutton:before,
#komodo_main #toolbox_side toolbaritem > toolbarbutton toolbarbutton:before,
#komodo_main #toolbox_side toolbaritem > toolbarbutton dropmarker:before {
	color: @foreground !important;
}
```
