### ISSUE TITLE
Border between stacked widgets (when customized) is REALLY hard to drag

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2073]
Customize the left or right panes by stacking two widgets on top of each other.  It's CRAZY hard to get your cursor to allow you to drag and resize the widgets.  See screenshot of where I'm talking about.  I think the border is only a single pixel.
![capture](https://cloud.githubusercontent.com/assets/655154/19006930/207d39fc-8717-11e6-99bb-a6d353d38149.PNG)

**Comment by Defman21** [comment]
For me any widget border is hard to drag. Resizing panes is PITA. Could you add a preference to change border width?

**Comment by cgchoffman** [comment]
I don't think a preference is necessary.  The area to drag should just be wider.  @Naatan is it possible to make the title bars of the widgets drag-able like the Projects title bar is drag-able in Places?

**Comment by Naatan** [comment]
Should be yeah.

**Comment by babobski** [comment]
To add a fix/workaround for the people that stumble upon this issue. 
You can add a small piece of [custom less](http://community.komodoide.com/t/komodo-x-customization-tips-tricks/2749/1) in **preferences > color scheme editor > interface** to fix this.

```less
// Make the splitter easier to handle
.widget_splitter[orient="vertical"],
#placesSubpanelSplitter[orient="vertical"] {
	padding-top: 2px !important;
	padding-bottom: 2px !important;
}
```

if you want it to make it more visible on hover you can do something like this:
```less
// Make the splitter easier to handle
.widget_splitter[orient="vertical"],
#placesSubpanelSplitter[orient="vertical"] {
	padding-top: 2px !important;
	padding-bottom: 2px !important;
	&:hover {
		background-color: fade(@border, 20%) !important;
	}
}
```
