### ISSUE TITLE
Editor: Tab-Aware Paste fails most of the time

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2805]
### Short Summary
I use the Editor: Tab-Aware Paste function on a daily basis, only the function fails most of the time.
I't only working for me with lines with the same indent. If the indent vary or there is a whitespace line in between, it fails. the function isn't that stable, I would love the see it get improved a bit.

Komodo 10.2.3 Windows 10

**Comment by mitchell-as** [comment]
Hi, thanks for the report. I need some examples in order to fix this though. Thank you.

**Comment by babobski** [comment]
More examples will follow soon, buut for example in less:
```less
#recreationBookForm {
	.control-label {
		text-align: left;
		color: @blue;
		font-size: 19px;
		line-height: 55px;
	}
	h3 {
		font-size: 18px;
		text-transform: uppercase;
		font-weight: 700;
	}
	.voorkeursboeking {
		margin: 25px 0;
		line-height: 55px;
		border-top: 1px solid rgba(0,0,0,0.15);
		border-bottom: 1px solid rgba(0,0,0,0.15);
		padding: 20px 0;
		.control-label {
			margin-left: -15px;
			color: #333;
		}
		.btn {
			margin-left: 15px;
		}
	}
	.booknow {
		text-transform: uppercase;
		padding: 20px;
		font-size: 32px !important;
	}
}
```
Let's say I want to move the `h3` and move it into `.voorkeursboeking` and use tab aware paste.
My result will look like:
```less
#recreationBookForm {
	.control-label {
		text-align: left;
		color: @blue;
		font-size: 19px;
		line-height: 55px;
	}
	.voorkeursboeking {
		margin: 25px 0;
		line-height: 55px;
		border-top: 1px solid rgba(0,0,0,0.15);
		border-bottom: 1px solid rgba(0,0,0,0.15);
		padding: 20px 0;
		h3 {
		font-size: 18px;
		text-transform: uppercase;
		font-weight: 700;
	}
		.control-label {
			margin-left: -15px;
			color: #333;
		}
		.btn {
			margin-left: 15px;
		}
	}
	.booknow {
		text-transform: uppercase;
		padding: 20px;
		font-size: 32px !important;
	}
}
```
What I excpect is:
```less
#recreationBookForm {
	.control-label {
		text-align: left;
		color: @blue;
		font-size: 19px;
		line-height: 55px;
	}
	.voorkeursboeking {
		margin: 25px 0;
		line-height: 55px;
		border-top: 1px solid rgba(0,0,0,0.15);
		border-bottom: 1px solid rgba(0,0,0,0.15);
		padding: 20px 0;
		h3 {
			font-size: 18px;
			text-transform: uppercase;
			font-weight: 700;
		}
		.control-label {
			margin-left: -15px;
			color: #333;
		}
		.btn {
			margin-left: 15px;
		}
	}
	.booknow {
		text-transform: uppercase;
		padding: 20px;
		font-size: 32px !important;
	}
}
```
