### ISSUE TITLE
Allow for use of $1 in regex find and replace

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2919]
### Short Summary
I wanted to preform a search and replace with regex, and use the group in the replace output.
It is only not replacing the $1 but just outputing $1

### Steps to Reproduce
Create a file with this content:
```less
.mfp-arrow {
	-webkit-user-select: none;
	-moz-user-select: none;
	user-select: none;
	position: absolute;
	opacity: 0.65;
	filter: alpha(opacity=65);
	margin: 0;
	top: 50%;
	margin-top: -55px;
	padding: 0;
	width: 90px;
	height: 110px;
	-webkit-tap-highlight-color: transparent;
	&:active {
		margin-top: -54px;
	}
	&:hover {
		opacity: 1;
		filter: alpha(opacity=100);
	}
	&:focus {
		opacity: 1;
		filter: alpha(opacity=100);
	}
	&:before {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 21px;
		border-bottom-width: 21px;
		opacity: 0.7;
	}
	&:after {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 13px;
		border-bottom-width: 13px;
		top: 8px;
	}
	.mfp-b {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 21px;
		border-bottom-width: 21px;
		opacity: 0.7;
	}
	.mfp-a {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 13px;
		border-bottom-width: 13px;
		top: 8px;
	}
}
```
In you're find field : `(alpha\(opacity\=[0-9'"]+\))`
And in you're replace: `~"$1"`

### Expected results
```less
.mfp-arrow {
	-webkit-user-select: none;
	-moz-user-select: none;
	user-select: none;
	position: absolute;
	opacity: 0.65;
	filter: ~"alpha(opacity=65)";
	margin: 0;
	top: 50%;
	margin-top: -55px;
	padding: 0;
	width: 90px;
	height: 110px;
	-webkit-tap-highlight-color: transparent;
	&:active {
		margin-top: -54px;
	}
	&:hover {
		opacity: 1;
		filter: ~"alpha(opacity=100)";
	}
	&:focus {
		opacity: 1;
		filter: ~"alpha(opacity=100)";
	}
	&:before {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 21px;
		border-bottom-width: 21px;
		opacity: 0.7;
	}
	&:after {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 13px;
		border-bottom-width: 13px;
		top: 8px;
	}
	.mfp-b {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 21px;
		border-bottom-width: 21px;
		opacity: 0.7;
	}
	.mfp-a {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 13px;
		border-bottom-width: 13px;
		top: 8px;
	}
}
```

### Actual results
```less
.mfp-arrow {
	-webkit-user-select: none;
	-moz-user-select: none;
	user-select: none;
	position: absolute;
	opacity: 0.65;
	filter: ~'$1';
	margin: 0;
	top: 50%;
	margin-top: -55px;
	padding: 0;
	width: 90px;
	height: 110px;
	-webkit-tap-highlight-color: transparent;
	&:active {
		margin-top: -54px;
	}
	&:hover {
		opacity: 1;
		filter: ~'$1';
	}
	&:focus {
		opacity: 1;
		filter: ~'$1';
	}
	&:before {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 21px;
		border-bottom-width: 21px;
		opacity: 0.7;
	}
	&:after {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 13px;
		border-bottom-width: 13px;
		top: 8px;
	}
	.mfp-b {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 21px;
		border-bottom-width: 21px;
		opacity: 0.7;
	}
	.mfp-a {
		content: '';
		display: block;
		width: 0;
		height: 0;
		position: absolute;
		left: 0;
		top: 0;
		margin-top: 35px;
		margin-left: 35px;
		border: medium inset transparent;
		border-top-width: 13px;
		border-bottom-width: 13px;
		top: 8px;
	}
}
```

### Platform Information

Komodo X.2.3 Windows 10

### Workarround
Create a userscript for this action.
```js
(function(){
	var koDoc = ko.views.manager.currentView.koDoc;
	if (koDoc !== 'undefined') {
		var buffer = koDoc.buffer;
		var newText = buffer.replace(/(alpha\(opacity\=[0-9'"]+\))/g, '~"$1"');
		
		koDoc.buffer = newText;
	}
}).apply();

```
