### ISSUE TITLE
Symbol browser missing top part of file ( less with media querys ) and broken a lot

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3202]
### Short Summary
I'm testing out the new symbol browser.
Only noticed in a less file with media querys it is missing it top part:
![afbeelding](https://user-images.githubusercontent.com/3530262/31044350-fb1fbc08-a5cd-11e7-9719-289b37d4fb29.png)

Note: also the rest of the symbol browser doesn't make any sense.
It is missing a lot of stuff, the part that is in comments is reversed.
It starts with // .cart-contents end end with // header.main-site-header, but in the code it is revered.
It shows a `:after`, but it is missing the `:before`.
Also it is showing one empty media query.
Looks a bit broken.

### Steps to Reproduce
Make a less file and paste:
```less

@media (min-width: 1330px) {
	#back-to-top {
		display: none !important;
	}
}

@media screen and (max-width: 1900px) {
	//header.main-site-header {
	//	#form-cart-wrapper {
	//		form {
	//			.search-field {
	//				width: 200px;
	//				padding: 10px;
	//			}
	//		}
	//		.cart-contents {
	//			margin-left: 20px;
	//		}
	//	}
	//}
	header.main-site-header {
		#productnav {
			ul {
				li {
					a {
						font-size: 16px;
					}
				}
			}
		}
	}
}

@media screen and (max-width: 1800px) {
	
}

@media screen and (max-width: 1700px) {
	.woocommerce {
		ul.products {
			li.product {
				.button {
					&:before {
						display: none;
					}
					&:after {
						display: none;
					}
					padding-right: 20px !important;
				}
			}
		}
	}
}

@media screen and (max-width: 1650px) {
	header.main-site-header {
		.menu-hoofd-menu-paginas-container {
			margin-left: 20px;
		}
		nav {
			figure {
				img {
					height: 90px;
					padding: 0;
				}
			}
		}
	}
}

@media screen and (max-width: 1550px) {
	
}

@media screen and (max-width: 1450px) {
	header.main-site-header {
		.menu-hoofd-menu-paginas-container {
			display: block !important;
		}
	}
}

@media screen and (max-width: 1300px) {
}

@media (max-width: 1200px) {
	header.main-site-header {
		#productnav {
			ul {
				li {
					a {
						font-size: 15px;
						padding: 10px 10px;
					}
				}
			}
		}
	}
	.menu-hoofd-menu-paginas-container {
		ul {
			li {
				a {
					font-size: 14px;
				}
			}
		}
	}
}

@media (max-width: 1150px) {
	header.main-site-header {
		#form-cart-wrapper {
			form {
				.search-field {
					width: 220px;
				}
			}
		}
	}
}

```

### Expected results
The sybol browser should start with `#back-to-top` ( or with the media query )

### Actual results
The sybol browser starts on line 17 with `.cart-contents`

### Platform Information

Komodo IDE, version 11.0.0, build 90668, platform win32-x86
