### ISSUE TITLE
Fold indicators broken in most css/less files

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3206]
### Short Summary
Was checking out the new symbol browser, but noticed it's broken most of the time.
I'm testing some media query issues, but in my css or less files the fold indicators are broken on some places.

![afbeelding](https://user-images.githubusercontent.com/3530262/31046179-9d152f4a-a5f4-11e7-9e26-1090c1d551aa.png)

![afbeelding](https://user-images.githubusercontent.com/3530262/31046187-bc00c0a4-a5f4-11e7-8d55-541ef1438c41.png)

![afbeelding](https://user-images.githubusercontent.com/3530262/31046193-ceee786e-a5f4-11e7-91fc-19410cc98dbe.png)

### Steps to Reproduce
Create a new less file and paste:
```less
.tax-product_cat,
.page-template {
	#single-page {
		.menu-product-categorie-menu-container,
		.menu-algemene-informatie-container {
			float: left;
			width: 20%;
			padding-left: 0 !important;
			li {
				list-style-type: none;
				position: relative;
				&:first-child {
					a {
						margin-top: 0 !important;
					}
				}
				a {
					color: @darkGrey;
					text-decoration: none;
					width: 100%;
					display: block;
					margin-top: 10px;
					-webkit-box-sizing: border-box !important;
					-moz-box-sizing: border-box !important;
					-ms-box-sizing: border-box !important;
					box-sizing: border-box !important;
				}
				&.current-menu-item {
					&:before {
						color: @lightBrown;
					}
					> a {
						color: @lightBrown;
					}
				}
				ul {
					li {
						a {
							margin-top: 0;
						}
						padding-left: 20px;
						position: relative;
						&:before {
							content: '\f105';
							font-family: 'FontAwesome';
							position: absolute;
							top: 3px;
							left: 5px;
							margin-top: 0;
						}
						&:first-child {
							margin-top: 8px;
						}
					}
				}
			}
			ul {
				padding: 0;
				margin: 0;
			}
		}
		.products {
			//clear: none !important;
			//float: right;
			//width: 80%;
			//-webkit-box-sizing: border-box !important;
			//-moz-box-sizing: border-box !important;
			//-ms-box-sizing: border-box !important;
			//box-sizing: border-box !important;
		}
		.term-description {
			clear: none !important;
			float: left;
			width: 100%;
			padding-left: 0px;
			-webkit-box-sizing: border-box !important;
			-moz-box-sizing: border-box !important;
			-ms-box-sizing: border-box !important;
			box-sizing: border-box !important;
			margin-top: 0 !important;
			p {
				padding-left: 0 !important;
				margin-top: 0 !important;
			}
		}
		h1 {
			clear: none !important;
			float: left;
			width: auto;
			padding-left: 0px;
			-webkit-box-sizing: border-box !important;
			-moz-box-sizing: border-box !important;
			-ms-box-sizing: border-box !important;
			box-sizing: border-box !important;
			font-size: 25px !important;
			margin-top: 0 !important;
		}
	}
	.woocommerce-result-count {
		display: none;
	}
	.woocommerce {
		//nav.woocommerce-pagination {
		//	text-align: right;
		//	position: relative;
		//	float: right;
		//	width: 100%;
		//}
	}
}

.pagination {
	text-align: right;
	margin-bottom: 10px;
	background-color: #f0f0f0;
	border-radius: 3px;
	width: 98%;
	border-bottom: 2px solid #dddddd;
	display: inline-block;
	white-space: nowrap;
	box-sizing: border-box;
	-webkit-box-sizing: border-box;
	li {
		border: none;
		display: inline-block;
		a {
			color: @black;
			font-weight: bold;
		}
	}
	vertical-align: top;
	span.page-numbers,
	a.page-numbers {
		padding: 12px 12px;
		text-align: center;
		display: inline-block;
		text-decoration: none;
		&.current {
			color: #333;
			//text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.3);
			background-color: #dcdcdc !important;
		}
		&:hover,
		&:focus,
		&:active {
			color: #333;
		}
		&.next,
		&.prev {
			text-align: center;
			font-size: 14px;
			line-height: 16px;
		}
	}
}

```
The fold indicator should be broken on line 142.

CSS example:
```css
.tax-product_cat #wppag {
  display: inline-block;
  width: 100%;
  text-align: right;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container,
.page-template #single-page .menu-product-categorie-menu-container,
.tax-product_cat #single-page .menu-algemene-informatie-container,
.page-template #single-page .menu-algemene-informatie-container {
  float: left;
  width: 20%;
  padding-left: 0 !important;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container li,
.page-template #single-page .menu-product-categorie-menu-container li,
.tax-product_cat #single-page .menu-algemene-informatie-container li,
.page-template #single-page .menu-algemene-informatie-container li {
  list-style-type: none;
  position: relative;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container li:first-child a,
.page-template #single-page .menu-product-categorie-menu-container li:first-child a,
.tax-product_cat #single-page .menu-algemene-informatie-container li:first-child a,
.page-template #single-page .menu-algemene-informatie-container li:first-child a {
  margin-top: 0 !important;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container li a,
.page-template #single-page .menu-product-categorie-menu-container li a,
.tax-product_cat #single-page .menu-algemene-informatie-container li a,
.page-template #single-page .menu-algemene-informatie-container li a {
  color: #414141;
  text-decoration: none;
  width: 100%;
  display: block;
  margin-top: 10px;
  -webkit-box-sizing: border-box !important;
  -moz-box-sizing: border-box !important;
  -ms-box-sizing: border-box !important;
  box-sizing: border-box !important;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container li.current-menu-item:before,
.page-template #single-page .menu-product-categorie-menu-container li.current-menu-item:before,
.tax-product_cat #single-page .menu-algemene-informatie-container li.current-menu-item:before,
.page-template #single-page .menu-algemene-informatie-container li.current-menu-item:before {
  color: #a56604;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container li.current-menu-item > a,
.page-template #single-page .menu-product-categorie-menu-container li.current-menu-item > a,
.tax-product_cat #single-page .menu-algemene-informatie-container li.current-menu-item > a,
.page-template #single-page .menu-algemene-informatie-container li.current-menu-item > a {
  color: #a56604;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container li ul li,
.page-template #single-page .menu-product-categorie-menu-container li ul li,
.tax-product_cat #single-page .menu-algemene-informatie-container li ul li,
.page-template #single-page .menu-algemene-informatie-container li ul li {
  padding-left: 20px;
  position: relative;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container li ul li a,
.page-template #single-page .menu-product-categorie-menu-container li ul li a,
.tax-product_cat #single-page .menu-algemene-informatie-container li ul li a,
.page-template #single-page .menu-algemene-informatie-container li ul li a {
  margin-top: 0;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container li ul li:before,
.page-template #single-page .menu-product-categorie-menu-container li ul li:before,
.tax-product_cat #single-page .menu-algemene-informatie-container li ul li:before,
.page-template #single-page .menu-algemene-informatie-container li ul li:before {
  content: '\f105';
  font-family: 'FontAwesome';
  position: absolute;
  top: 3px;
  left: 5px;
  margin-top: 0;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container li ul li:first-child,
.page-template #single-page .menu-product-categorie-menu-container li ul li:first-child,
.tax-product_cat #single-page .menu-algemene-informatie-container li ul li:first-child,
.page-template #single-page .menu-algemene-informatie-container li ul li:first-child {
  margin-top: 8px;
}
.tax-product_cat #single-page .menu-product-categorie-menu-container ul,
.page-template #single-page .menu-product-categorie-menu-container ul,
.tax-product_cat #single-page .menu-algemene-informatie-container ul,
.page-template #single-page .menu-algemene-informatie-container ul {
  padding: 0;
  margin: 0;
}
.tax-product_cat #single-page .term-description,
.page-template #single-page .term-description {
  clear: none !important;
  float: left;
  width: 100%;
  padding-left: 0px;
  -webkit-box-sizing: border-box !important;
  -moz-box-sizing: border-box !important;
  -ms-box-sizing: border-box !important;
  box-sizing: border-box !important;
  margin-top: 0 !important;
}
.tax-product_cat #single-page .term-description p,
.page-template #single-page .term-description p {
  padding-left: 0 !important;
  margin-top: 0 !important;
}
.tax-product_cat #single-page h1,
.page-template #single-page h1 {
  clear: none !important;
  float: left;
  width: auto;
  padding-left: 0px;
  -webkit-box-sizing: border-box !important;
  -moz-box-sizing: border-box !important;
  -ms-box-sizing: border-box !important;
  box-sizing: border-box !important;
  font-size: 25px !important;
  margin-top: 0 !important;
}
.tax-product_cat .woocommerce-result-count,
.page-template .woocommerce-result-count {
  display: none;
}
.pagination {
  text-align: right;
  margin-bottom: 10px;
  background-color: #f0f0f0;
  border-radius: 3px;
  width: 98%;
  border-bottom: 2px solid #dddddd;
  display: inline-block;
  white-space: nowrap;
  box-sizing: border-box;
  -webkit-box-sizing: border-box;
  vertical-align: top;
}
.pagination li {
  border: none;
  display: inline-block;
}
.pagination li a {
  color: #383736;
  font-weight: bold;
}
.pagination span.page-numbers,
.pagination a.page-numbers {
  padding: 12px 12px;
  text-align: center;
  display: inline-block;
  text-decoration: none;
}
```
The fold indicator is broken on line 141

### Platform Information

Komodo IDE, version 11.0.0, build 90668, platform win32-x86
