### ISSUE TITLE
Apply color scheme doesn't affect console

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3248]
### Short Summary
I was testing for a question on the form, but I noticed the console doesn't get affected when applying the css changes. You need to reboot for the changes to take affect.

### Steps to Reproduce
I don't know if what the differences are between OS's, but for tested on Windows you can use the following snippet.

```less
#console {
	#output {
		font-size: 1.4rem !important;
		line-height: 1.4rem !important;
		*,
		*::-moz-tree-cell-text {
			font-size: 1.4rem !important;
			line-height: 1.4rem !important;
		}
		> li {
			&:not(.input) {
				font-size: 1.4rem !important;
				line-height: 1.4rem !important;
			}
			&:before {
				font-size: 1.2rem !important;
				line-height: 1.2rem !important;
			}
			.message li.complex-format ul {
				font-size: 1.2rem !important;
			}
		}
	}
}
```
If you then apply the changes, nothing changes in the console.
If you know reboot, the changes are applied.

### Expected results
Using the apply button in the color-scheme window, should also affect the console area.

### Actual results
You need to reboot Komodo

### Platform Information
Komodo Ide 10 -11 Windows 10

### Additional Information

If you want to tweak the less to you're needs and want a faster way to reboot Komodo, you can use the following user-script:

```javascript
Components.classes["@mozilla.org/toolkit/app-startup;1"]
.getService(Components.interfaces.nsIAppStartup)
.quit(
Components.interfaces.nsIAppStartup.eRestart |
Components.interfaces.nsIAppStartup.eAttemptQuit
);
```

You can also easy create it into a toolbar button.

1. Create a custom toolbar.

![afbeelding](https://user-images.githubusercontent.com/3530262/31239007-fc7ff36a-a9fb-11e7-989a-7c30a9d01706.png)

2. Add a user-script to you're new toolbar

![afbeelding](https://user-images.githubusercontent.com/3530262/31239220-ad2b9214-a9fc-11e7-8684-2eb6f8ddb6be.png)

3. Pick a nice icon

![afbeelding](https://user-images.githubusercontent.com/3530262/31239293-ede1ea4c-a9fc-11e7-9345-be1c879db6f5.png)

Then you will have a nice reboot button in you're toolbar.

![afbeelding](https://user-images.githubusercontent.com/3530262/31239371-26bf2636-a9fd-11e7-9136-cac417a6afb9.png)
