### ISSUE TITLE
If you use a tab instead of a space after a attribute breaks highlighting ( LESS )

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3260]
### Short Summary
I opened a Less file in K11 only noticed  that the highlighting was broken on some spaces.
Noticed that where it was broken, it was using tabs instead of spaces.

![afbeelding](https://user-images.githubusercontent.com/3530262/31429108-66cb3bf6-ae6d-11e7-93d1-1d905a5e8773.png)

### Steps to Reproduce
 * Create a new less file
 * Create or copy paste the example from below

You will see the highlighting is broken.
Also tested it in normal CSS, but here the issue is not appearing.

Example:
```less
#header {
	background-color:	rgba(0, 0, 0, 0.2); // This line uses a tab
	color: #FFF;
	border:	1px solid rgba(0, 0, 0, 0.4); // This line uses a tab
	border-radius: 4px;
}
```

### Platform Information

Komodo IDE, version 11.0.0, build 90668, platform win32-x86.
