### ISSUE TITLE
!important's failing on some cases.

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3296]
### Short Summary
Noticed that on some cases, the auto completion for the !important is missing.
Look like it has to do with some of the characters.

### Steps to Reproduce
 * Create a css file
 * Paste the content form below
 * Try to auto complete for !important

Test code:
```css
.test {
	content '';
	opacity: 0.1;
	filter: blur(3px);
	letter-spacing: 2px;
	white-space: pre-wrap;
	box-sizing: border-box;
}
```

### Expected results
It would auto complete for `!important`.

### Actual results
The auto completion is missing or now auto completion is shown at all

### Platform Information

Komodo IDE, version 11.0.1, build 90791, platform win32-x86
