### ISSUE TITLE
Completions not working on white space in CSS files

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3550]
### Short Summary

```css
.blah
{
    width: 10px;
    background: center;
    border: <|> I should get a bunch of completions here
}
```
You have to backspace to the colon to get completions.
