### ISSUE TITLE
CSS2 identifiers are highlighted as tags in <style> tags

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#53]
![html](http://i.imgur.com/Iw1Fi9l.png)
![css](http://i.imgur.com/FHtU5yP.png)

**Comment by Naatan** [comment]
Could you please provide the actual code snippets for easy reproduction? :)

**Comment by Defman21** [comment]
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <style>
    * {
      border: 1px solid #fff; /* CSS 2 keywords */
      animation: myanim; /* CSS 3 keywowrds */
    }
  </style>
</body>
</html>
```
```css
* {
  border: 1px solid #fff; /* CSS 2 keywords */
  animation: myanim; /* CSS 3 keywowrds */
}
```
