### ISSUE TITLE
CSS Codeintel doesn't show me a class if it's a child class

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#678]
```css
#test .me {
color: red;
}
```

```html
<div id="|[1]">
<span class="|[2]">
</div>
```
At `|[1]`, I get `test` (so it works fine).
At `|[2]`, I get nothing - so it doesn't work.
