### ISSUE TITLE
CSS: Invalid icon for child classes/tags in Code Browser/Commando Sections Scope

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#679]
```css
#test .me {
color: red;
}
```
Code Browser shows that `#test .me` is an id (but it's a class actually).
Commando just doesn't display an icon for this (as for ids, but I'll report about it separately) 
```css
#test div {
color: red;
}
```
Code Browser shows that `#test div` is an id (but it's a tag actually).
